spring:
  mail:
    host: smtp.qq.com
    port: 25
    username: mail@qq.com
    password: password

mail:
  default:
    from: mail@qq.com
    to: mail@mail.com

splitter:
  output-dir: ./output
  volume-size: 20971520 # 20MB

file-path: /Users/ayachinene/Desktop/DSC_0369-已增强.dng
